X = MsgBox("You have a virus",16,"Virus")
X = MsgBox("Woo AntiVirus may attempt to delete this Virus. However, you must wire 100 bitcoin to the following Address: Myballs0430924.com.",32+1,"Do you agree?")
X = MsgBox("Attemping to delete the virus...",0,"Woo AntiVirus")
X = MsgBox("Attemping to delete the virus...",0,"Woo AntiVirus")
X = MsgBox("Attemping to delete the virus...",0,"Woo AntiVirus")
X = MsgBox("In order to delete the virus, you must agree that Issac Woo has an IQ of 1000000 and Danny Kwong has an IQ of -63. ",32+3,"Woo AntiVirus")
X = MsgBox("AUTOMATICALLY AGREEING!",48+0,"Woo Antivirus")
X = MsgBox("The virus is now deleted.",48+0,"ADIOS!")